info:
  title: STD2311 - TD1
  version: 1.0.0

servers:
  - url: https://localhost.STD2311.com

paths:
  /customers:
    get:
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "http://localhost.STDXXX.com/components/schemas/Customer"

components:
  schemas:
    Customer:
      type: object
      properties:
        name:
          type: string
        yearsOld:
          type: integer
