openapi: 3.0.3
info:
  title: STD23111 - TD1
  version: 1.0.0
servers:
  - url: https://localhost.STD2311.com
paths:
  /customers:
    get:
      responses:
        200:
          description: List of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"
components:
  schemas:
    Customer:
      type: object
      properties:
        name:
          type: string
        yearsOld:
          type: integer
  