openapi: 3.0.3
info:
  title: STD23111 - TD2
  version: 1.0.4
servers:
  - url: http://localhost:3000
paths:
  /meal:
    get:
      summary: Récupérer la liste de tous les plats
      responses:
        '200':
          description: Liste de plats récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
    post:
      summary: Créer un nouveau plat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MealCreation'
      responses:
        '201':
          description: Plat créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meal'
  /meal/{id}:
    put:
      summary: Mettre à jour un plat par identifiant
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Identifiant unique du plat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MealUpdate'
      responses:
        '200':
          description: Plat mis à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meal'
        '404':
          description: Plat non trouvé
    delete:
      summary: Supprimer un plat par identifiant
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Identifiant unique du plat
      responses:
        '204':
          description: Plat supprimé avec succès
        '404':
          description: Plat non trouvé
  /customers/{customerId}/orders:
    get:
      summary: Récupérer la liste des commandes d'un client
      parameters:
        - in: path
          name: customerId
          required: true
          schema:
            type: string
          description: Identifiant unique du client
      responses:
        '200':
          description: Liste des commandes récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      summary: Ajouter une nouvelle commande pour un client
      parameters:
        - in: path
          name: customerId
          required: true
          schema:
            type: string
          description: Identifiant unique du client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreation'
      responses:
        '201':
          description: Commande créée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
  /customers/{customerId}/orders/{orderId}:
    put:
      summary: Mettre à jour une commande existante d'un client
      parameters:
        - in: path
          name: customerId
          required: true
          schema:
            type: string
          description: Identifiant unique du client
        - in: path
          name: orderId
          required: true
          schema:
            type: string
          description: Identifiant unique de la commande
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderUpdate'
      responses:
        '200':
          description: Commande mise à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Commande non trouvée
components:
  schemas:
    Meal:
      type: object
      properties:
        id:
          type: string
          description: Identifiant unique du plat
        name:
          type: string
          description: Nom du plat
        price:
          type: number
          format: float
          description: Prix du plat
      required:
        - id
        - name
        - price
    MealCreation:
      type: object
      properties:
        name:
          type: string
          description: Nom du plat
        price:
          type: number
          format: float
          description: Prix du plat
      required:
        - name
        - price
    MealUpdate:
      type: object
      properties:
        name:
          type: string
          description: Nom du plat
        price:
          type: number
          format: float
          description: Prix du plat
      required:
        - name
        - price
    Order:
      type: object
      properties:
        id:
          type: string
          description: Identifiant unique de la commande
        reference:
          type: string
          description: Numéro de commande unique
        meals:
          type: array
          items:
            type: object
            properties:
              meal:
                $ref: '#/components/schemas/Meal'
              quantity:
                type: integer
                description: Quantité du plat commandé
        orderDatetime:
          type: string
          format: date-time
          description: Date et heure de la commande
      required:
        - id
        - reference
        - meals
        - orderDatetime
    OrderCreation:
      type: object
      properties:
        reference:
          type: string
          description: Numéro de commande unique
        meals:
          type: array
          items:
            type: object
            properties:
              mealId:
                type: string
                description: Identifiant du plat
              quantity:
                type: integer
                description: Quantité du plat commandé
      required:
        - reference
        - meals
    OrderUpdate:
      type: object
      properties:
        reference:
          type: string
          description: Numéro de commande unique
        meals:
          type: array
          items:
            type: object
            properties:
              mealId:
                type: string
                description: Identifiant du plat
              quantity:
                type: integer
                description: Quantité du plat commandé
      required:
        - reference
        - meals
